import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <div className='flex flex-col max-w-2xl mx-auto pt-10 items-center'>
            <Header />
            <main className="flex flex-col items-center justify-between p-12 gap-10">
              {children}
            </main>
          </div>
        </ClerkProvider>
      </body>
    </html>
  )
}
